import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/global/Footer";
import Header from "@/components/global/Header";
import { FacebookIcon, InstagramIcon, LinkdinIcon, LocationIcon, MailBoxIcon, PhoneIcon, TwitterIcon } from "@/common/icons";
import 'react-phone-input-2/lib/style.css';
import FormSecton from "@/components/global/FormSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Xizec-The X factor in IT Consulting",
  description: "Generated by create next app",
};

const footerData = {
  logo: {
    url: "/images/mainlogo.png",
    alt: "Xizec Logo",
    name: "The Future of IT Consulting",
  },
  col1: {
    title: "Sitemap",
    links: [
      { href: "/", text: "Home" },
      { href: "/about", text: "About" },
      { href: "/services", text: "Services" },
      { href: "/portfolio", text: "Portfolio" },
      { href: "/contact", text: "Contact" },
    ],
  },
  col2: {
    title: "Links",
    links: [
      { href: "/privacy", text: "Privacy Policy" },
      { href: "/terms", text: "Terms of Service" },
      { href: "/cookies", text: "Cookie Policy" },
    ],
  },
  col3: [
    {
      text: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
      icon: <LocationIcon/>,
      type: "location",
    },
    {
      text: "sara.cruz@example.com",
      icon:  <MailBoxIcon/>,
      type: "email",
    },
    {
      text: "(239) 555-0108",
      icon:  <PhoneIcon/>,
      type: "phone",
    },
  ],
  socialLinks: [
    { href: "https://facebook.com", icon:  <FacebookIcon/>, isExternal: true },
    { href: "https://instagram.com", icon:  <InstagramIcon/>, isExternal: true },
    { href: "https://linkedin.com", icon:  <LinkdinIcon/>, isExternal: true },
    { href: "https://twitter.com", icon:  <TwitterIcon/>, isExternal: true },
  ],
  copyrightText: "Copyright ©2025 XIZEC",
};


const formData = {
  title:"Let’s Build Your Next Big IT Success",
  subtitle:"At XIZEC, we turn ideas into impactful solutions with expert IT consulting, digital transformation, and future-ready strategies. Share your vision with us—we’ll make it happen.",
  cols3: [
    {
      text: "2972 Westheimer Rd. Santa Ana, Illinois 85486",
      icon: <LocationIcon/>,
      type: "location",
    },
    {
      text: "sara.cruz@example.com",
      icon:  <MailBoxIcon/>,
      type: "email",
    },
    {
      text: "(239) 555-0108",
      icon:  <PhoneIcon/>,
      type: "phone",
    },
  ],
  socialLinks: [
    { href: "https://facebook.com", icon:  <FacebookIcon/>, isExternal: true },
    { href: "https://instagram.com", icon:  <InstagramIcon/>, isExternal: true },
    { href: "https://linkedin.com", icon:  <LinkdinIcon/>, isExternal: true },
    { href: "https://twitter.com", icon:  <TwitterIcon/>, isExternal: true },
  ],
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <FormSecton data={formData}/>
        <Footer {...footerData}/>
      </body>
    </html>
  );
}
